# Site settings
title: Alberto Estrada - Portfolio
email: albertoe@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Senior web developer with a experience of more than 7 years.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://albertoestrada.codes" # the base hostname & protocol for your site
twitter_username: cyberkiko
github_username:  cyberkiko
linkedin_username: cyberkiko

# Build settings
markdown: kramdown

#gems
gems:
  - octopress-autoprefixer
